#ifndef QUICKWEBSHORTCUTS_API_LANGUAGE_UTILITY_H
#define QUICKWEBSHORTCUTS_API_LANGUAGE_UTILITY_H

#include <QtWidgets/QComboBox>

void setBingLanguages(QComboBox *box) {
    box->clear();
    box->addItem("ar-sa (Arabic)", "ar-sa");
    box->addItem("da-dk (Danish)", "da-dk");
    box->addItem("de-at (German-Austria)", "de-at");
    box->addItem("de-ch (German-Switzerland)", "de-ch");
    box->addItem("de-de (German-Germany)", "de-de");
    box->addItem("en-au (English-Australia)", "en-au");
    box->addItem("en-ca (English-Canada)", "en-ca");
    box->addItem("en-gb (English-UK)", "en-gb");
    box->addItem("en-id (English-Indonesia)", "en-id");
    box->addItem("en-ie (English-Ireland)", "en-ie");
    box->addItem("en-in (English-India)", "en-in");
    box->addItem("en-my (English-Malaysia)", "en-my");
    box->addItem("en-mx (English-Mexico)", "en-mx");
    box->addItem("en-nz (English-New Zealand)", "en-nz");
    box->addItem("en-ph (English-Philippines)", "en-ph");
    box->addItem("en-us (English-United States)", "en-us");
    box->addItem("en-za (English-South Africa)", "en-za");
    box->addItem("es-ar (Spanish-Argentina)", "es-ar");
    box->addItem("es-cl (Spanish-Chile)", "es-cl");
    box->addItem("es-mx (Spanish-Mexico)", "es-mx");
    box->addItem("es-es (Spanish-Spain)", "es-es");
    box->addItem("es-us (Spanish-United States)", "es-us");
    box->addItem("fi-fi (Finnish)", "fi-fi");
    box->addItem("fr-be (French-Belgium)", "fr-be");
    box->addItem("fr-ca (French-Canada)", "fr-ca");
    box->addItem("fr-ch (French-Switzerland)", "fr-ch");
    box->addItem("fr-fr (French-France)", "fr-fr");
    box->addItem("it-it (Italian)", "it-it");
    box->addItem("ja-jp (Japanese)", "ja-jp");
    box->addItem("ko-kr (Korean)", "ko-kr");
    box->addItem("nl-be (Dutch-Belgium)", "nl-be");
    box->addItem("nl-nl (Dutch_Netherlands)", "nl-nl");
    box->addItem("no-no (Norwegian)", "no-no");
    box->addItem("pl-pl (Polish)", "pl-pl");
    box->addItem("pt-pt (Portuguese-Portugal)", "pt-pt");
    box->addItem("pt-br (Portuguese-Brazil)", "pt-br");
    box->addItem("ru-ru (Russian)", "ru-ru");
    box->addItem("sv-se (Swedish)", "sv-se");
    box->addItem("tr-tr (Turkish)", "tr-tr");
    box->addItem("zh-cn (Chinese)", "zh-cn");
    box->addItem("zh-hk (Traditional Chinese-Hong Kong SAR)", "zh-hk");
    box->addItem("zh-tw (Traditional Chinese-Taiwan)", "zh-tw");
}

void setGoogleLanguages(QComboBox *box) {
    box->clear();
    // https://sites.google.com/site/tomihasa/google-language-codes
    box->addItem("Afrikaans", "af");
    box->addItem("Akan", "ak");
    box->addItem("Albanian", "sq");
    box->addItem("Amharic", "am");
    box->addItem("Arabic", "ar");
    box->addItem("Armenian", "hy");
    box->addItem("Azerbaijani", "az");
    box->addItem("Basque", "eu");
    box->addItem("Belarusian", "be");
    box->addItem("Bemba", "bem");
    box->addItem("Bengali", "bn");
    box->addItem("Bihari", "bh");
    box->addItem("Bork, bork, bork!", "xx-bork");
    box->addItem("Bosnian", "bs");
    box->addItem("Breton", "br");
    box->addItem("Bulgarian", "bg");
    box->addItem("Cambodian", "km");
    box->addItem("Catalan", "ca");
    box->addItem("Cherokee", "chr");
    box->addItem("Chichewa", "ny");
    box->addItem("Chinese (Simplified)", "zh-CN");
    box->addItem("Chinese (Traditional)", "zh-TW");
    box->addItem("Corsican", "co");
    box->addItem("Croatian", "hr");
    box->addItem("Czech", "cs");
    box->addItem("Danish", "da");
    box->addItem("Dutch", "nl");
    box->addItem("Elmer Fudd", "xx-elmer");
    box->addItem("English", "en");
    box->addItem("Esperanto", "eo");
    box->addItem("Estonian", "et");
    box->addItem("Ewe", "ee");
    box->addItem("Faroese", "fo");
    box->addItem("Filipino", "tl");
    box->addItem("Finnish", "fi");
    box->addItem("French", "fr");
    box->addItem("Frisian", "fy");
    box->addItem("Ga", "gaa");
    box->addItem("Galician", "gl");
    box->addItem("Georgian", "ka");
    box->addItem("German", "de");
    box->addItem("Greek", "el");
    box->addItem("Guarani", "gn");
    box->addItem("Gujarati", "gu");
    box->addItem("Hacker", "xx-hacker");
    box->addItem("Haitian Creole", "ht");
    box->addItem("Hausa", "ha");
    box->addItem("Hawaiian", "haw");
    box->addItem("Hebrew", "iw");
    box->addItem("Hindi", "hi");
    box->addItem("Hungarian", "hu");
    box->addItem("Icelandic", "is");
    box->addItem("Igbo", "ig");
    box->addItem("Indonesian", "id");
    box->addItem("Interlingua", "ia");
    box->addItem("Irish", "ga");
    box->addItem("Italian", "it");
    box->addItem("Japanese", "ja");
    box->addItem("Javanese", "jw");
    box->addItem("Kannada", "kn");
    box->addItem("Kazakh", "kk");
    box->addItem("Kinyarwanda", "rw");
    box->addItem("Kirundi", "rn");
    box->addItem("Klingon", "xx-klingon");
    box->addItem("Kongo", "kg");
    box->addItem("Korean", "ko");
    box->addItem("Krio (Sierra Leone)", "kri");
    box->addItem("Kurdish", "ku");
    box->addItem("Kurdish (Soranî)", "ckb");
    box->addItem("Kyrgyz", "ky");
    box->addItem("Laothian", "lo");
    box->addItem("Latin", "la");
    box->addItem("Latvian", "lv");
    box->addItem("Lingala", "ln");
    box->addItem("Lithuanian", "lt");
    box->addItem("Lozi", "loz");
    box->addItem("Luganda", "lg");
    box->addItem("Luo", "ach");
    box->addItem("Macedonian", "mk");
    box->addItem("Malagasy", "mg");
    box->addItem("Malay", "ms");
    box->addItem("Malayalam", "ml");
    box->addItem("Maltese", "mt");
    box->addItem("Maori", "mi");
    box->addItem("Marathi", "mr");
    box->addItem("Mauritian Creole", "mfe");
    box->addItem("Moldavian", "mo");
    box->addItem("Mongolian", "mn");
    box->addItem("Montenegrin", "sr-ME");
    box->addItem("Nepali", "ne");
    box->addItem("Nigerian Pidgin", "pcm");
    box->addItem("Northern Sotho", "nso");
    box->addItem("Norwegian", "no");
    box->addItem("Norwegian (Nynorsk)", "nn");
    box->addItem("Occitan", "oc");
    box->addItem("Oriya", "or");
    box->addItem("Oromo", "om");
    box->addItem("Pashto", "ps");
    box->addItem("Persian", "fa");
    box->addItem("Pirate", "xx-pirate");
    box->addItem("Polish", "pl");
    box->addItem("Portuguese (Brazil)", "pt-BR");
    box->addItem("Portuguese (Portugal)", "pt-PT");
    box->addItem("Punjabi", "pa");
    box->addItem("Quechua", "qu");
    box->addItem("Romanian", "ro");
    box->addItem("Romansh", "rm");
    box->addItem("Runyakitara", "nyn");
    box->addItem("Russian", "ru");
    box->addItem("Scots Gaelic", "gd");
    box->addItem("Serbian", "sr");
    box->addItem("Serbo-Croatian", "sh");
    box->addItem("Sesotho", "st");
    box->addItem("Setswana", "tn");
    box->addItem("Seychellois Creole", "crs");
    box->addItem("Shona", "sn");
    box->addItem("Sindhi", "sd");
    box->addItem("Sinhalese", "si");
    box->addItem("Slovak", "sk");
    box->addItem("Slovenian", "sl");
    box->addItem("Somali", "so");
    box->addItem("Spanish", "es");
    box->addItem("Spanish (Latin American)", "es-419");
    box->addItem("Sundanese", "su");
    box->addItem("Swahili", "sw");
    box->addItem("Swedish", "sv");
    box->addItem("Tajik", "tg");
    box->addItem("Tamil", "ta");
    box->addItem("Tatar", "tt");
    box->addItem("Telugu", "te");
    box->addItem("Thai", "th");
    box->addItem("Tigrinya", "ti");
    box->addItem("Tonga", "to");
    box->addItem("Tshiluba", "lua");
    box->addItem("Tumbuka", "tum");
    box->addItem("Turkish", "tr");
    box->addItem("Turkmen", "tk");
    box->addItem("Twi", "tw");
    box->addItem("Uighur", "ug");
    box->addItem("Ukrainian", "uk");
    box->addItem("Urdu", "ur");
    box->addItem("Uzbek", "uz");
    box->addItem("Vietnamese", "vi");
    box->addItem("Welsh", "cy");
    box->addItem("Wolof", "wo");
    box->addItem("Xhosa", "xh");
    box->addItem("Yiddish", "yi");
    box->addItem("Yoruba", "yo");
    box->addItem("Zulu", "zu");
}

#endif //QUICKWEBSHORTCUTS_API_LANGUAGE_UTILITY_H
